spring:
  application:
    name: reminderBot
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5443}/${DB_NAME:reminder}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driverClassName:
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: true

application:
  reminders-batch-size: 10

telegram:
  bot-name: ${BOT_NAME:remind_demo_bot}
  token: ${TLG_API_KEY}
